version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: sudo pip install .
          name: Install twistream
      - run:
          command: black --check --line-length 120 .
          name: Black formatting
      - run:
          command: mypy twistream
          name: Type checking - myPy
      - run:
          command: pytest tests -vv
          name: Run tests

workflows:
  main:
    jobs:
      - build-and-test
