twitter:
  customer_key: your_customer_key
  customer_secret: your_customer_secret
  acces_token_key: your_acces_token_key
  acces_token_secret: your_acces_token_secret

logging:
  log_level: INFO

persist:
  engine: sqlite
