twitter:
  consumer_key: your_consumer_key
  consumer_secret: your_consumer_secret
  access_token: your_acces_token
  access_token_secret: your_acces_token_secret

backend: backend_name

backend_params:
  db: twistream

